### PR TITLE
Add ci with github actions

### LINKED ISSUE #20: CircleCI builds are broken
Apparently CircleCI no longer supports projects with a 1.0 configuration.

[Service alert](https://circleci.com/gh/def-/nim-bigints): Your project references CircleCI 1.0 or it has no configuration. CircleCI 1.0 and projects without configuration files are no longer supported. You must update your project to use CircleCI 2.0 configuration to continue.

### PR DESCRIPTION
**Pull request by pietroppeter**
add CI using github actions using proven methodology by @jiro4989  (see e.g. here https://github.com/HugoGranstrom/symbolicnim/pull/2).

also:

* remove old CI (circle). this fixes #20
* added test badge on readme (equivalent for original repo of what you see here: https://github.com/pietroppeter/nim-bigints/workflows/test/badge.svg)

### CODE REVIEW

**Comment by def-** [comment]
Great, thanks!

**Comment by pietroppeter** [comment]
Thank you!

I noticed that Circle CI is still reporting as failed, is it possible that something else other than removing configuration file needs to be done in order for github to foget about it?

image

**Comment by pietroppeter** [comment]
yep, found it: https://discuss.circleci.com/t/remove-circleci-from-github-repo/1144

> go to repo settings, Webhooks and Services, and delete the CircleCi webhook.

**Comment by def-** [comment]
Done.

**Pull request merged**
